version: '3.6'

services:
  support-bot-telegram:
    build:
      context: .
    env_file:
      - .env
    command:
      /bot_application/entrypoint.sh telegram
    volumes:
      - ./data:/bot_application/data

  support-bot-vk:
    build:
      context: .
    env_file:
      - .env
    command:
       /bot_application/entrypoint.sh vk
    volumes:
      - ./data:/bot_application/data

  init-intents:
    build:
      context: .
    env_file:
      - .env
    command:
       /bot_application/entrypoint.sh init
    volumes:
      - ./data:/bot_application/data