version: '3.6'

services:
  support-bot-telegram:
    build:
      context: .
    working_dir:
      /bot_application
    env_file:
      - .env
    command:
      /bot_application/entrypoint.sh telegram
    volumes:
      - ./data:/data
      - ./application:/bot_application/application/

  support-bot-vk:
    build:
      context: .
    working_dir:
      /bot_application
    env_file:
      - .env
    command:
       /bot_application/entrypoint.sh vk
    volumes:
      - ./data:/data
      - ./application:/bot_application/application/

  init-intents:
    build:
      context: .
    working_dir:
      /bot_application
    env_file:
      - .env
    command:
       /bot_application/entrypoint.sh init
    volumes:
      - ./data:/data
      - ./application:/bot_application/application/