version: '3.6'

services:
  support-bot-telegram:
    build:
      context: .
    env_file:
      - .env
    command:
      /bot_application/entrypoint.sh
    volumes:
      - ./data:/bot_application/data

  support-bot-vk:
    build:
      context: .
    env_file:
      - .env
    command:
      /bot_application/entrypoint-telegram.sh
    volumes:
      - ./data:/bot_application/data
